name: CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Rodar lint
        run: npm run lint || true

      - name: Rodar testes
        run: npm test -- --watchAll=false || true

      - name: Build do projeto
        run: DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Build Docker image
        run: docker build -t tcs-pointer-front .